apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${cluster_auth_base64}
    server: https://${cluster_endpoint}
  name: ${cluster_name}
contexts:
- context:
    cluster: ${cluster_name}
    user: ${cluster_name}-admin
  name: ${cluster_name}-admin
current-context: ${cluster_name}-admin
kind: Config
preferences: {}
users:
- name: ${cluster_name}-admin
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
  